# Generated by Django 5.0.14 on 2026-06-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessgroup',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='demand',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
