# Generated by Django 5.0.14 on 2026-06-22 16:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def seed_default_locations(apps, schema_editor):
    Location = apps.get_model('service', 'Location')
    Block = apps.get_model('service', 'Block')
    ServiceRequest = apps.get_model('service', 'ServiceRequest')
    location, _ = Location.objects.get_or_create(nome='ICET', defaults={'active': True})
    for block_name in ['Bloco A', 'Bloco B', 'Bloco C', 'Bloco D', 'Bloco Administrativo']:
        Block.objects.get_or_create(location=location, nome=block_name, defaults={'active': True})
    ServiceRequest.objects.filter(local='').update(local='ICET')


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_user_failed_login_attempts_user_locked_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'locations',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='local',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.ForeignKey(db_column='location_id', on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='service.location')),
            ],
            options={
                'db_table': 'blocks',
                'ordering': ['location__nome', 'nome'],
                'unique_together': {('location', 'nome')},
            },
        ),
        migrations.RunPython(seed_default_locations, migrations.RunPython.noop),
    ]
