# Generated by Django 5.0.14 on 2026-06-22 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_location_servicerequest_local_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='assigned_user',
            field=models.ForeignKey(blank=True, db_column='assigned_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='service.user'),
        ),
    ]
